import type { ReportSections } from "./report-template.js";
import { renderReportDocument } from "./report-template.js";

export interface ReportExportInput {
  reportNumber: string;
  problem: string;
  machine?: string;
  date: string;
  engineer: string;
  status: string;
  version: number;
  sections?: ReportSections | null;
  content: string;
  organization?: string;
}

export function renderPrintableHtml(report: ReportExportInput): string {
  const plainBody = report.sections
    ? renderReportDocument(
        {
          reportNumber: report.reportNumber,
          problem: report.problem,
          date: report.date,
          engineer: report.engineer,
          status: report.status,
          ...(report.machine ? { machine: report.machine } : {})
        },
        report.sections
      )
    : report.content;

  const escaped = plainBody
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

  return `<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="utf-8" />
  <title>${report.reportNumber} — Investigation Report</title>
  <style>
    @page { margin: 2cm; }
    body { font-family: "Segoe UI", Arial, sans-serif; color: #111; max-width: 800px; margin: 0 auto; padding: 24px; }
    h1 { text-align: center; font-size: 18px; letter-spacing: 0.15em; margin-bottom: 8px; }
    hr { border: none; border-top: 1px solid #333; margin: 16px 0; }
    pre { white-space: pre-wrap; font-family: "Courier New", monospace; font-size: 12px; line-height: 1.6; }
    .meta { font-size: 11px; color: #555; text-align: center; margin-bottom: 24px; }
    .footer { margin-top: 32px; font-size: 10px; color: #888; text-align: center; }
    @media print { body { padding: 0; } }
  </style>
</head>
<body>
  <div class="meta">${report.organization ?? "Buek Core"} · v${report.version} · ${report.status.toUpperCase()}</div>
  <pre>${escaped}</pre>
  <div class="footer">Generated by Buek Core — Official Investigation Document</div>
  <script>window.onload = () => { if (new URLSearchParams(location.search).get('print') === '1') window.print(); };</script>
</body>
</html>`;
}
