import type { ReportSections } from "./report-template.js";
import { renderReportDocument } from "./report-template.js";

export interface ReportExportInput {
  reportNumber: string;
  problem: string;
  machine?: string;
  date: string;
  engineer: string;
  status: string;
  version: number;
  sections?: ReportSections | null;
  content: string;
  organization?: string;
  reportTitle?: string;
  brandColor?: string;
  industryLabel?: string;
}

export function renderPrintableHtml(report: ReportExportInput): string {
  const plainBody = report.sections
    ? renderReportDocument(
        {
          reportNumber: report.reportNumber,
          problem: report.problem,
          date: report.date,
          engineer: report.engineer,
          status: report.status,
          ...(report.machine ? { machine: report.machine } : {})
        },
        report.sections
      )
    : report.content;

  const escaped = plainBody
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

  const brand = report.brandColor ?? "#2563eb";
  const title = report.reportTitle ?? "INVESTIGATION REPORT";
  const orgLine = [report.organization, report.industryLabel].filter(Boolean).join(" · ");

  return `<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="utf-8" />
  <title>${report.reportNumber} — ${title}</title>
  <style>
    @page { margin: 2cm; }
    body { font-family: "Segoe UI", Arial, sans-serif; color: #111; max-width: 800px; margin: 0 auto; padding: 24px; }
    .brand-bar { height: 4px; background: ${brand}; margin-bottom: 24px; border-radius: 2px; }
    h1 { text-align: center; font-size: 16px; letter-spacing: 0.12em; margin-bottom: 8px; color: ${brand}; }
    hr { border: none; border-top: 1px solid #ccc; margin: 16px 0; }
    pre { white-space: pre-wrap; font-family: "Courier New", monospace; font-size: 12px; line-height: 1.6; }
    .meta { font-size: 11px; color: #555; text-align: center; margin-bottom: 24px; }
    .footer { margin-top: 32px; font-size: 10px; color: #888; text-align: center; border-top: 1px solid #eee; padding-top: 16px; }
    @media print { body { padding: 0; } }
  </style>
</head>
<body>
  <div class="brand-bar"></div>
  <h1>${title}</h1>
  <div class="meta">${orgLine || "Buek Core"} · ${report.reportNumber} · v${report.version} · ${report.status.toUpperCase()}</div>
  <pre>${escaped}</pre>
  <div class="footer">Official document generated by Buek Core Enterprise AI Platform</div>
  <script>window.onload = () => { if (new URLSearchParams(location.search).get('print') === '1') window.print(); };</script>
</body>
</html>`;
}
